import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Legal Reader</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/Icons/folders.ico" />
				<link
					rel="stylesheet"
					href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
					integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
					crossorigin="anonymous"
					referrerpolicy="no-referrer"
				/>
			</Head>
			<main className={`${styles.bodyContainer} ${inter.className}`}>
				<div className={styles.container}>
					<div className={styles.inputContainer}>
						<input
							className={styles.queryInput}
							type="text"
							id="queryField"
						/>
						<button className="sttInput"></button>
					</div>
				</div>
			</main>
		</>
	);
}
